[tool.bumpversion]
current_version = "1.2.1"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "dateparser/__init__.py"

[[tool.bumpversion.files]]
filename = 'HISTORY.rst'
search = "\\(unreleased\\)$"
replace = "({now:%Y-%m-%d})"
regex = true

[tool.ruff]
exclude = ["date_translation_data"]

[tool.ruff.lint.per-file-ignores]
"dateparser/data/__init__.py" = ["F401"]
"dateparser/languages/__init__.py" = ["F401"]
